SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES';
SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, AUTOCOMMIT=0;

START TRANSACTION;

-- sort_order type should be int not string
UPDATE `document_files` SET `sort_order` = '0' WHERE `sort_order` IS NULL;
ALTER TABLE `document_files` MODIFY `sort_order` INTEGER NOT NULL DEFAULT 0;

-- Date of document creation on server must always be set.
UPDATE `documents` SET `server_date_created` = '' WHERE `server_date_created` IS NULL;
ALTER TABLE `documents` MODIFY `server_date_created` VARCHAR(50) NOT NULL COMMENT 'Date of insertion into the database (is generated by the system).';

COMMIT;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;

