SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES';
SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, AUTOCOMMIT=0;

START TRANSACTION;

-- Extend length of selected fields in documents table
ALTER TABLE `documents` MODIFY COLUMN `edition` VARCHAR(255) NULL COMMENT 'Edition of a monograph.';
ALTER TABLE `documents` MODIFY COLUMN `issue` VARCHAR(255) NULL COMMENT 'Issue.';
ALTER TABLE `documents` MODIFY COLUMN `volume` VARCHAR(255) NULL COMMENT 'Volume.';

COMMIT;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;

