-- This file is part of OPUS. The software OPUS has been developed at the
-- University of Stuttgart with funding from the German Research Net
-- (Deutsches Forschungsnetz), the Federal Department of Higher Education and
-- Research (Bundesministerium fuer Bildung und Forschung) and The Ministry of
-- Science, Research and the Arts of the State of Baden-Wuerttemberg
-- (Ministerium fuer Wissenschaft, Forschung und Kunst des Landes
-- Baden-Wuerttemberg).
-- 
-- PHP versions 4 and 5
-- 
-- OPUS is free software; you can redistribute it and/or
-- modify it under the terms of the GNU General Public License
-- as published by the Free Software Foundation; either version 2
-- of the License, or (at your option) any later version.
-- 
-- OPUS is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
-- 
-- You should have received a copy of the GNU General Public License
-- along with OPUS; if not, write to the Free Software Foundation,
-- Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 
-- @package     Opus
-- @author      Ralf Claussnitzer <ralf.claussnitzer@slub-dresden.de>
-- @copyright   Universitaetsbibliothek Stuttgart, 1998-2008
-- @license     http://www.gnu.org/licenses/gpl.html
-- @version     $Id$

SET CHARACTER SET UTF8;

-- *****************************************************************************
-- NOTE:
--
-- Everything below this block gets generated by DBDesigner when changes occur.
-- Altering those statements might lead to loss of information.
-- 
-- *****************************************************************************

CREATE TABLE `RESOURCES` (
  `RESOURCE_ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  PRIMARY KEY(`RESOURCE_ID`)
)
TYPE=InnoDB;

CREATE TABLE `DOCUMENT_TYPES` (
  `DOCUMENT_TYPE_ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  PRIMARY KEY(`DOCUMENT_TYPE_ID`),
  UNIQUE INDEX `DOCUMENT_TYPE_UNIQUE`(`NAME`)
)
TYPE=InnoDB;

CREATE TABLE `SITES` (
  `SITE_ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NULL,
  `FULL_NAME` VARCHAR(100) NULL,
  PRIMARY KEY(`SITE_ID`),
  INDEX `SITE_unique`(`NAME`)
)
TYPE=InnoDB;

CREATE TABLE `ROLES` (
  `ROLE_ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  PRIMARY KEY(`ROLE_ID`)
)
TYPE=InnoDB;

CREATE TABLE `DOCUMENTS` (
  `DOCUMENT_ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `DOCUMENT_TYPE_ID` INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(`DOCUMENT_ID`),
  FOREIGN KEY(`DOCUMENT_TYPE_ID`)
    REFERENCES `DOCUMENT_TYPES`(`DOCUMENT_TYPE_ID`)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
)
TYPE=InnoDB;

CREATE TABLE `ACCOUNTS` (
  `ACCOUNT_ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `SITE_ID` INTEGER UNSIGNED NOT NULL,
  `USERNAME` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  PRIMARY KEY(`ACCOUNT_ID`),
  INDEX `ACCOUNT_FKIndex1`(`SITE_ID`),
  UNIQUE INDEX `ACCOUNT_unique`(`USERNAME`),
  FOREIGN KEY(`SITE_ID`)
    REFERENCES `SITES`(`SITE_ID`)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
)
TYPE=InnoDB;

CREATE TABLE `DOCUMENT_MULTIVALUES` (
  `MULTIVALUE_ID` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DOCUMENT_ID` INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(`MULTIVALUE_ID`, `DOCUMENT_ID`),
  INDEX `DOCUMENT_LIST_FKIndex1`(`DOCUMENT_ID`),
  FOREIGN KEY(`DOCUMENT_ID`)
    REFERENCES `DOCUMENTS`(`DOCUMENT_ID`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
TYPE=InnoDB;

CREATE TABLE `FIELD_DEFINITIONS` (
  `FIELD_DEFINITION_ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `DOCUMENT_TYPE_ID` INTEGER UNSIGNED NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `TYPE` ENUM('TEXT','NUMBER','DATE','BOOLEAN') NOT NULL,
  `MULTIVALUE` BOOL NOT NULL DEFAULT 0,
  `IS_MANDATORY` BOOL NOT NULL DEFAULT 0,
  PRIMARY KEY(`FIELD_DEFINITION_ID`, `DOCUMENT_TYPE_ID`),
  FOREIGN KEY(`DOCUMENT_TYPE_ID`)
    REFERENCES `DOCUMENT_TYPES`(`DOCUMENT_TYPE_ID`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
TYPE=InnoDB;

CREATE TABLE `ROLE_has_RESOURCE` (
  `RESOURCE_ID` INTEGER UNSIGNED NOT NULL,
  `ROLE_ID` INTEGER UNSIGNED NOT NULL,
  `allowed` BOOL NOT NULL DEFAULT 0,
  PRIMARY KEY(`RESOURCE_ID`, `ROLE_ID`),
  INDEX `ROLE_has_RESOURCE_FKIndex1`(`ROLE_ID`),
  INDEX `ROLE_has_RESOURCE_FKIndex2`(`RESOURCE_ID`),
  FOREIGN KEY(`ROLE_ID`)
    REFERENCES `ROLES`(`ROLE_ID`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(`RESOURCE_ID`)
    REFERENCES `RESOURCES`(`RESOURCE_ID`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
TYPE=InnoDB;

CREATE TABLE `ACCOUNT_has_ROLE` (
  `ACCOUNT_ID` INTEGER UNSIGNED NOT NULL,
  `ROLE_ID` INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(`ACCOUNT_ID`, `ROLE_ID`),
  INDEX `ACCOUNT_has_ROLE_FKIndex1`(`ACCOUNT_ID`),
  INDEX `ACCOUNT_has_ROLE_FKIndex2`(`ROLE_ID`),
  FOREIGN KEY(`ACCOUNT_ID`)
    REFERENCES `ACCOUNTS`(`ACCOUNT_ID`)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(`ROLE_ID`)
    REFERENCES `ROLES`(`ROLE_ID`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
TYPE=InnoDB;